#!/bin/sh
cd /work/stratum-mining

set -e

until mysql -h"db" -u"root" -p"$MYSQL_ROOT_PASSWORD" &> /dev/null
do
    >&2 echo "MySQL is unavailable - sleeping"
    sleep 1
done

>&2 echo "MySQL is up - executing command"

memcached -d -uroot
twistd -ny launcher.tac
